println("Scala type tree from top to bottom")
println("1) Any")
println("2) AnyVal or AnyRef")
println("3.1) AnyVal -> Numeric Types, Char, Boolean")
println("3.2) AnyRef -> Collections, Classes, String")
println("4) Null - for AnyRef")
println("5) Nothing - for everything")
println()
println("Casting data types - dataType1.asInstanceOf[dataType2]")
println("5.asInstanceOf[Float] " +  5.asInstanceOf[Float])

println("Casting data types - dataType1.toDataType")
println("5.toFloat " + 5.toFloat)
println("Returning class name - dataType1.getClass")
println("5.getClass "  + 5.getClass)
println("Checking data types - dataType1.isInstanceOf[dataType2]")
println("5.isInstanceOf[Float]" + 5.isInstanceOf[Float])
println("Hashing - dataType1.hashCode")
println("\"ABC\".hashCode " + "ABC".hashCode)
println("Casting to string - dataType1.toString")
println("5.toString " + 5.toString)
